---
- name: Simple Backup Example
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Get running config
      cisco.ios.ios_command:
        commands: show running-config
      register: result

    - name: Show first line
      debug:
        msg: "First line: {{ result.stdout_lines[0][0] if result.stdout_lines[0] else 'Empty' }}"
